// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4ffuXwWgsrHLeG1_77I0u1JVgVB_uvw',
    appId: '1:10645149408:web:12a6bf0eb8d813fc11e285',
    messagingSenderId: '10645149408',
    projectId: 'vieclamsv-a9383',
    authDomain: 'vieclamsv-a9383.firebaseapp.com',
    storageBucket: 'vieclamsv-a9383.firebasestorage.app',
    measurementId: 'G-73KWNVZ3ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQhxm9bmo2eKJCr6jG7oPkX6xTDfY51Yw',
    appId: '1:10645149408:android:5124f939fc5ba7d211e285',
    messagingSenderId: '10645149408',
    projectId: 'vieclamsv-a9383',
    storageBucket: 'vieclamsv-a9383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCor0cWJDl-0dmorro4SnDp78cq8_s1SMc',
    appId: '1:10645149408:ios:713b4a52c2a97abb11e285',
    messagingSenderId: '10645149408',
    projectId: 'vieclamsv-a9383',
    storageBucket: 'vieclamsv-a9383.firebasestorage.app',
    iosBundleId: 'com.example.flutteProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCor0cWJDl-0dmorro4SnDp78cq8_s1SMc',
    appId: '1:10645149408:ios:713b4a52c2a97abb11e285',
    messagingSenderId: '10645149408',
    projectId: 'vieclamsv-a9383',
    storageBucket: 'vieclamsv-a9383.firebasestorage.app',
    iosBundleId: 'com.example.flutteProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4ffuXwWgsrHLeG1_77I0u1JVgVB_uvw',
    appId: '1:10645149408:web:739075e4926c5bd711e285',
    messagingSenderId: '10645149408',
    projectId: 'vieclamsv-a9383',
    authDomain: 'vieclamsv-a9383.firebaseapp.com',
    storageBucket: 'vieclamsv-a9383.firebasestorage.app',
    measurementId: 'G-ZE6J3BZ7S1',
  );
}
